### ISSUE TITLE
RunTimeError: Numpy is not available

### ISSUE THREAD

**Issue by ShashankKrishnaV** [Yuliang-Liu/Monkey#100]
I am not sure why this error is occurring while running the inference file

`warnings.warn(
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.17k/1.17k [00:00<00:00, 121kB/s]
configuration_qwen.py: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.09k/2.09k [00:00<00:00, 185kB/s]
A new version of the following files was downloaded from https://huggingface.co/echo840/Monkey-Chat:
- configuration_qwen.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
modeling_monkey.py: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.17k/6.17k [00:00<00:00, 558kB/s]

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/nvme/scratch/shashank_kv/LLMs/Monkey/inference.py", line 16, in <module>
    model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map='cuda', trust_remote_code=True).eval()
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 503, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 174, in check_imports
    importlib.import_module(imp)
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/peft/mapping.py", line 22, in <module>
    from .mixed_model import PeftMixedModel
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/peft/mixed_model.py", line 26, in <module>
    from peft.tuners.mixed import COMPATIBLE_TUNER_TYPES
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/peft/tuners/__init__.py", line 22, in <module>
    from .loha import LoHaConfig, LoHaModel
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/peft/tuners/loha/__init__.py", line 16, in <module>
    from .layer import Conv2d, Linear, LoHaLayer
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/peft/tuners/loha/layer.py", line 302, in <module>
    class HadaWeight(torch.autograd.Function):
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/peft/tuners/loha/layer.py", line 304, in HadaWeight
    def forward(ctx, w1a, w1b, w2a, w2b, scale=torch.tensor(1)):
/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/peft/tuners/loha/layer.py:304: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  def forward(ctx, w1a, w1b, w2a, w2b, scale=torch.tensor(1)):
A new version of the following files was downloaded from https://huggingface.co/echo840/Monkey-Chat:
- modeling_monkey.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
pytorch_model.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19.4G/19.4G [12:03<00:00, 26.9MB/s]
Your device does NOT seem to support bf16, you can switch to fp16 or fp32 by by passing fp16/fp32=True in "AutoModelForCausalLM.from_pretrained".
Traceback (most recent call last):
  File "/nvme/scratch/shashank_kv/LLMs/Monkey/inference.py", line 16, in <module>
    model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map='cuda', trust_remote_code=True).eval()
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/home/shashank_kv/scratch/miniconda3/envs/textmonkey/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2876, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/shashank_kv/scratch/cache/huggingface/modules/transformers_modules/echo840/Monkey-Chat/8a447049636331e3c8ba9a92f5021c70914f8351/modeling_monkey.py", line 101, in __init__
    super().__init__(config)
  File "/home/shashank_kv/scratch/cache/huggingface/modules/transformers_modules/echo840/Monkey-Chat/8a447049636331e3c8ba9a92f5021c70914f8351/modeling_qwen.py", line 780, in __init__
    self.transformer = QWenModel(config)
  File "/home/shashank_kv/scratch/cache/huggingface/modules/transformers_modules/echo840/Monkey-Chat/8a447049636331e3c8ba9a92f5021c70914f8351/modeling_qwen.py", line 503, in __init__
    self.visual = VisionTransformer(**config.visual)
  File "/home/shashank_kv/scratch/cache/huggingface/modules/transformers_modules/echo840/Monkey-Chat/8a447049636331e3c8ba9a92f5021c70914f8351/visual.py", line 476, in __init__
    self.attn_pool = Resampler(
  File "/home/shashank_kv/scratch/cache/huggingface/modules/transformers_modules/echo840/Monkey-Chat/8a447049636331e3c8ba9a92f5021c70914f8351/visual.py", line 132, in __init__
    torch.from_numpy(get_2d_sincos_pos_embed(embed_dim, grid_size)).float()
RuntimeError: Numpy is not available`

**Comment by tujianxin** [comment]
hello,ShashankKrishnaV,I have encounter the same problem,could you tell me how deal with it?thank you!
