### ISSUE TITLE
运行inference.py报错，不知道什么问题

### ISSUE THREAD

**Issue by caolingen2022** [Yuliang-Liu/Monkey#109]
2024-07-26 14:39:34.501338: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-26 14:39:34.658117: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-26 14:39:34.691101: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-26 14:39:35.242071: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2024-07-26 14:39:35.242147: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2024-07-26 14:39:35.242159: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/jovyan/Monkey-main/inference.py", line 12, in <module>
    model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map='cuda:4', trust_remote_code=True,from_tf=True).eval()
  File "/opt/conda/envs/monkey/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 559, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/envs/monkey/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3882, in from_pretrained
    model, loading_info = load_tf2_checkpoint_in_pytorch_model(
  File "/opt/conda/envs/monkey/lib/python3.9/site-packages/transformers/modeling_tf_pytorch_utils.py", line 523, in load_tf2_checkpoint_in_pytorch_model
    tf_model_class = getattr(transformers, tf_model_class_name)
  File "/opt/conda/envs/monkey/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1579, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers has no attribute TFMonkeyLMHeadModel

**Comment by echo840** [comment]
您是用tensorflow运行的吗，我们没有尝试在tensorflow上运行过我们的模型。
