### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sangyuJ** [Yuliang-Liu/Monkey#148]
Hi author, I encounter this error while training the model. I wonder if it is the problem with DeepSpeed version.
Traceback (most recent call last):
  File "/home/jisangyu/monkey/Monkey/finetune_multitask.py", line 406, in <module>
    train()
  File "/home/jisangyu/monkey/Monkey/finetune_multitask.py", line 389, in train
    trainer.train()
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.9/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.9/site-packages/transformers/trainer.py", line 1684, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.9/site-packages/accelerate/accelerator.py", line 1220, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.9/site-packages/accelerate/accelerator.py", line 1605, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.9/site-packages/deepspeed/__init__.py", line 181, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 308, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1293, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1551, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 283, in __init__
    self.dtype = self.optimizer.param_groups[0]['params'][0].dtype
IndexError: list index out of range

**Comment by echo840** [comment]
Hello, our deepspeed version is 0.11.1.
![image](https://github.com/user-attachments/assets/6290e68d-4439-4a30-a39b-31529299a7e8)
