### ISSUE TITLE
OOM error while pre-training the model on 3090 24G

### ISSUE THREAD

**Issue by sangyuJ** [Yuliang-Liu/Monkey#151]
Hi author, I've used lora and modeling_qwen_nvdia3090.py to train the model. However, I am still encountering a CUDA out of memory error. Could you tell me how to solve it?

Traceback (most recent call last):
  File "/home/jisangyu/monkey/Monkey/finetune_multitask.py", line 437, in <module>
    train()
  File "/home/jisangyu/monkey/Monkey/finetune_multitask.py", line 420, in train
    trainer.train()
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/transformers/trainer.py", line 1837, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/transformers/trainer.py", line 2693, in training_step
    self.accelerator.backward(loss)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/accelerate/accelerator.py", line 1960, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 2020, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2063, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/jisangyu/anaconda3/envs/monkey/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 594.00 MiB (GPU 0; 23.65 GiB total capacity; 21.43 GiB already allocated; 221.00 MiB free; 21.83 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|                                       | 1/90596 [00:36<912:05:10, 36.24s/it]

**Comment by echo840** [comment]
Hello, we trained Monkey using 80G A800. You can try MiniMonkey, which can be trained on 8 RTX 3090 GPUs.
