### ISSUE TITLE
 OOM Issue on 8x40G A100 GPUs Despite Adjustments and Use of modeling_qwen_nvidia3090.py

### ISSUE THREAD

**Issue by jweihe** [Yuliang-Liu/Monkey#64]
**Description**
I am experiencing an Out-of-Memory (OOM) issue when running our code on a setup with 8x40G A100 GPUs. Despite replacing modeling_qwen.py with the contents of modeling_qwen_nvidia3090.py, the issue persists. Below is the script used for executing the training process, including the environment setup and distributed training arguments:
```
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=$(pwd)

GPUS_PER_NODE=8
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=9808

MODEL="Qwen/Qwen-VL" # We use the first version of Qwen-VL
DATA="/data/train/train_monkey.json"

DISTRIBUTED_ARGS="--nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT"

torchrun $DISTRIBUTED_ARGS finetune_multitask.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --fp16 False \
    --fix_vit True \
    --output_dir output_model_test2 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.02 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 2048 \
    --gradient_checkpointing \
    --lazy_preprocess True \
    --deepspeed /Monkey/finetune/ds_config_zero2.json \
    --use_lora True \
    --data_path /data/train/train_monkey.json
```

**Additional Information: Error Traceback**
When running the code, the following error traceback was encountered, indicating a CUDA Out-of-Memory (OOM) issue:
```
Traceback (most recent call last):
  File "finetune_multitask.py", line 407, in <module>
    os.environ["PYTHONHASHSEED"] = str(seed)
  File "finetune_multitask.py", line 390, in train
    model=model, tokenizer=tokenizer, args=training_args, **data_module
  File "[...]/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "[...]/site-packages/transformers/trainer.py", line 1837, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "[...]/site-packages/transformers/trainer.py", line 2682, in training_step
    loss = self.compute_loss(model, inputs)
  File "[...]/site-packages/transformers/trainer.py", line 2707, in compute_loss
    outputs = model(**inputs)
  File "[...]/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "[...]/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "[...]/site-packages/deepspeed/runtime/engine.py", line 1852, in forward
    loss = self.module(*inputs, **kwargs)
  File "[...]/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  ...
  File "[...]/site-packages/torch/nn/modules/module.py", line 209, in forward
    up = up * self.lora_scale
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 39.59 GiB total capacity; 36.98 GiB already allocated; 13.19 MiB free; 37.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Request for Assistance**
I am seeking help to:

> Identify potential causes for the OOM issue in our current setup.

> Suggest any configuration changes or optimizations that might help in resolving this problem.

> Any insights on whether the problem is specific to the model architecture or the setup.

Thank you in advance for any assistance or suggestions you can provide！

**Comment by XenoZLH** [comment]
Hello, thanks for following Monkey!<br>
Like the original QWen model, Monkey model's LoRA layers were added manually. In order to setup LoRA training, you need to make some modifications in `finetune_multitask.py` as the README mentioned.<br>
Delete the original codes for LoRA training at `#line350` and add following codes:<br>
```
if training_args.use_lora:
    # delete the default codes
    model.transformer.requires_grad_(False)
        # freeze llm as the REAMDE required
        model.lm_head.requires_grad_(False)
        model.transformer.visual.requires_grad_(False)
        if hasattr(model.transformer.visual, 'attn_pool'):
            model.transformer.visual.attn_pool.requires_grad_(True)

        # only keep the gradient of lora and resampler module
        for k, v in model.named_parameters():
            if "lora" in k:
                v.requires_grad_(True)
        for k, v in model.named_parameters():
            if "window_attention" in k:
                v.requires_grad_(True)

    if training_args.fix_llm and hasattr(model, 'transformer') and hasattr(model.transformer, 'h'):
        model.transformer.h.requires_grad_(False)
        model.transformer.wte.requires_grad_(False)

    if training_args.gradient_checkpointing:
        model.enable_input_require_grads()
```
By applying the modifications above, it should be ok to setup the LoRA training of Monkey. Note that an `fix_llm` parameter needs to be added to `TrainingArguments` and its value set to `True` to freeze the unnecessary parameters.<br>
Attention, according to our experiment, it requires about 19GB memory to load the entire model before the first training step, so it is very likely to experience Out-of-Memory issue when running on RTX 3090 with only 24GB memory. To address this issue, you may have to use checkpoint mechanism.<br>
For example, adding checkpoint at `#line70` in `modeling_monkey.py`:<br>
```
import torch.utils.checkpoint as cp
...
# line 70
for image_patch in col:
    # adding checkpoint in the forward process
    temp = torch.new_zeros(image_patch.shape, dtype=image_patch.dtype, device=image_patch.device, requires_grad=True)
    image_patch = image_patch + temp
    patch_list.append(cp.checkpoint(self.visual, image_patch, lora_idx))
    lora_idx += 1
...
```
This may slow down the training speed, but make it possible to train Monkey on 24GB devices. For 40GB devices, maybe this step is not necessary. Also, you can modify the codes to add checkpoint at other part of the forward process.<br>
I hope this can solve your problems.

**Comment by jweihe** [comment]
@XenoZLH Which layers should be trained with LoRa here?
